-- ============================================
-- Seed Data
-- ============================================

-- Site Settings
INSERT INTO public.site_settings (key, value, type, group_name) VALUES
('hero_title', 'We Build Digital Experiences That Matter', 'text', 'hero'),
('hero_subtitle', 'SilverArch is a full-service digital agency crafting elegant web solutions for ambitious brands.', 'text', 'hero'),
('hero_cta_text', 'Start Your Project', 'text', 'hero'),
('hero_cta_url', '/contact', 'text', 'hero'),
('site_name', 'SilverArch', 'text', 'general'),
('site_description', 'Full-service digital agency specializing in web development, design, and digital strategy.', 'text', 'general'),
('contact_email', 'hello@silverarch.dev', 'text', 'general'),
('contact_phone', '+1 (555) 123-4567', 'text', 'general'),
('contact_address', '123 Innovation Drive, San Francisco, CA 94107', 'text', 'general');

-- Services
INSERT INTO public.services (title, slug, short_description, long_description, icon, features, benefits, display_order) VALUES
('Web Development', 'web-development', 'Custom web applications built with modern frameworks and best practices.', '## Custom Web Development\n\nWe build fast, scalable web applications using cutting-edge technologies. From single-page apps to complex enterprise platforms, our team delivers clean, maintainable code that performs.\n\nOur development process ensures every project is built on a solid foundation with modern architecture patterns, comprehensive testing, and performance optimization.', 'Globe', '["Next.js & React", "TypeScript", "Responsive Design", "API Integration", "Performance Optimization", "SEO Best Practices"]', '["Faster load times", "Better user engagement", "Scalable architecture", "Lower maintenance costs"]', 1),
('UI/UX Design', 'ui-ux-design', 'Beautiful, intuitive interfaces designed to delight users and drive conversions.', '## UI/UX Design Services\n\nGreat design is more than aesthetics — it is about creating intuitive experiences that guide users toward their goals. We combine research, strategy, and creativity to deliver interfaces that look stunning and perform beautifully.\n\nFrom wireframes to polished prototypes, we ensure every pixel serves a purpose.', 'Palette', '["User Research", "Wireframing", "Prototyping", "Design Systems", "Usability Testing", "Brand Identity"]', '["Higher conversion rates", "Improved user satisfaction", "Consistent brand experience", "Reduced development time"]', 2),
('E-Commerce', 'e-commerce', 'Scalable online stores that convert visitors into customers.', '## E-Commerce Solutions\n\nWhether you need a Shopify store or a fully custom e-commerce platform, we build online stores that drive sales. Our solutions include payment integration, inventory management, and analytics to help you grow.\n\nWe focus on the entire customer journey — from landing page to checkout — optimizing every step for maximum conversion.', 'ShoppingCart', '["Shopify & Custom Stores", "Payment Integration", "Inventory Management", "Analytics Dashboard", "SEO Optimization", "Mobile Commerce"]', '["Increased sales", "Better customer experience", "Streamlined operations", "Data-driven decisions"]', 3),
('Digital Strategy', 'digital-strategy', 'Data-driven strategies to grow your digital presence and reach your goals.', '## Digital Strategy & Consulting\n\nWe help businesses navigate the digital landscape with clear, actionable strategies. From market analysis to growth hacking, our consultants work alongside your team to identify opportunities and execute plans that deliver measurable results.', 'TrendingUp', '["Market Analysis", "SEO Strategy", "Content Planning", "Growth Hacking", "Analytics & Reporting", "Competitor Analysis"]', '["Clear roadmap", "Measurable ROI", "Competitive advantage", "Sustainable growth"]', 4),
('Mobile Apps', 'mobile-apps', 'Native and cross-platform mobile applications for iOS and Android.', '## Mobile App Development\n\nWe create mobile applications that users love. Whether you need a native iOS/Android app or a cross-platform solution, we deliver polished, performant apps that work seamlessly across devices.\n\nOur mobile team specializes in React Native and Flutter for efficient cross-platform development without sacrificing quality.', 'Smartphone', '["React Native", "Flutter", "iOS & Android", "Push Notifications", "Offline Support", "App Store Optimization"]', '["Wider reach", "Better engagement", "Native performance", "Single codebase"]', 5),
('SEO & Marketing', 'seo-marketing', 'Comprehensive SEO and digital marketing to drive organic growth.', '## SEO & Digital Marketing\n\nVisibility is everything in the digital world. Our SEO and marketing team uses proven strategies to improve your search rankings, drive qualified traffic, and convert visitors into customers.\n\nWe combine technical SEO, content strategy, and data analytics to deliver sustainable organic growth.', 'TrendingUp', '["Technical SEO", "Content Marketing", "Link Building", "Local SEO", "PPC Management", "Social Media"]', '["Higher rankings", "More organic traffic", "Better conversion rates", "Brand authority"]', 6);

-- Packages
INSERT INTO public.packages (name, slug, description, monthly_price, yearly_price, features, is_popular, cta_text, display_order) VALUES
('Starter', 'starter', 'Perfect for small businesses just getting started online.', 2499, 24990, '[{"text":"5-page website","included":true},{"text":"Responsive design","included":true},{"text":"Basic SEO setup","included":true},{"text":"Contact form","included":true},{"text":"1 round of revisions","included":true},{"text":"CMS integration","included":false},{"text":"Custom animations","included":false},{"text":"Priority support","included":false}]', false, 'Get Started', 1),
('Professional', 'professional', 'For growing businesses that need a strong digital presence.', 4999, 49990, '[{"text":"10-page website","included":true},{"text":"Responsive design","included":true},{"text":"Advanced SEO","included":true},{"text":"Contact form + CRM","included":true},{"text":"3 rounds of revisions","included":true},{"text":"CMS integration","included":true},{"text":"Custom animations","included":true},{"text":"Priority support","included":false}]', true, 'Get Started', 2),
('Enterprise', 'enterprise', 'Full-scale digital solutions for established businesses.', NULL, NULL, '[{"text":"Unlimited pages","included":true},{"text":"Responsive design","included":true},{"text":"Advanced SEO","included":true},{"text":"Custom forms + integrations","included":true},{"text":"Unlimited revisions","included":true},{"text":"CMS integration","included":true},{"text":"Custom animations","included":true},{"text":"Priority support","included":true}]', false, 'Contact Us', 3);

-- Projects
INSERT INTO public.projects (title, slug, short_description, long_description, client_name, category, tags, tech_stack, results, is_featured, display_order) VALUES
('Nexus SaaS Platform', 'nexus-saas', 'A comprehensive SaaS platform for project management and team collaboration.', '## Project Overview\n\nNexus needed a modern project management platform that could scale with their growing user base. We built a full-featured SaaS application with real-time collaboration, task management, and analytics.\n\n## Challenge\n\nThe client needed a platform that could handle thousands of concurrent users while maintaining fast load times and a smooth user experience.\n\n## Solution\n\nWe chose Next.js with TypeScript for the frontend, paired with Supabase for the backend. Real-time features were built using Supabase Realtime, and the entire application was deployed on Vercel for optimal performance.', 'Nexus Inc.', 'Web App', '["SaaS", "Dashboard", "Real-time"]', '["Next.js", "TypeScript", "Supabase", "Tailwind CSS", "Vercel"]', '[{"metric": "Load Time", "value": "< 1.5s"},{"metric": "User Growth", "value": "300%"},{"metric": "Uptime", "value": "99.9%"}]', true, 1),
('Velocity E-Commerce', 'velocity-ecommerce', 'A high-performance e-commerce store with custom checkout flow and inventory management.', '## Project Overview\n\nVelocity is a premium fashion brand that needed an e-commerce platform matching their brand quality. We delivered a custom Shopify Plus store with unique design elements and optimized checkout flow.\n\n## Challenge\n\nThe existing store had a 70% cart abandonment rate and poor mobile performance. The client needed a complete overhaul.\n\n## Solution\n\nWe redesigned the entire shopping experience with a focus on mobile-first design, streamlined checkout, and personalized product recommendations.', 'Velocity Fashion', 'E-Commerce', '["Shopify", "Fashion", "Mobile-first"]', '["Shopify Plus", "React", "Node.js", "Stripe"]', '[{"metric": "Conversion Rate", "value": "+45%"},{"metric": "Cart Abandonment", "value": "-30%"},{"metric": "Revenue", "value": "+60%"}]', true, 2),
('Pulse Analytics', 'pulse-analytics', 'Real-time analytics dashboard for monitoring business metrics and KPIs.', '## Project Overview\n\nPulse needed a way to visualize complex data from multiple sources in real-time. We built a custom analytics dashboard with interactive charts, automated reports, and alerting.\n\n## Challenge\n\nData was scattered across multiple platforms with no unified view. The team was spending hours manually compiling reports.\n\n## Solution\n\nWe built a centralized dashboard that pulls data from all sources via APIs, processes it in real-time, and presents it through intuitive visualizations.', 'DataPulse Corp', 'SaaS', '["Analytics", "Dashboard", "Data Viz"]', '["React", "D3.js", "PostgreSQL", "Python", "AWS"]', '[{"metric": "Reporting Time", "value": "-85%"},{"metric": "Data Sources", "value": "12+"},{"metric": "Daily Users", "value": "500+"}]', true, 3);

-- Testimonials
INSERT INTO public.testimonials (client_name, client_title, client_company, content, rating, is_featured, display_order) VALUES
('Sarah Chen', 'CEO', 'TechFlow', 'SilverArch transformed our online presence completely. The attention to detail and the quality of work exceeded our expectations. Our conversion rate increased by 40% after the redesign.', 5, true, 1),
('Marcus Rivera', 'Founder', 'Velocity', 'Working with SilverArch was a game-changer. They delivered a stunning e-commerce platform that our customers love. The team was professional, responsive, and truly understood our vision.', 5, true, 2),
('Emily Watson', 'CTO', 'DataPulse', 'The SaaS dashboard SilverArch built for us is incredibly intuitive and performant. They handled complex data visualization requirements with ease. Highly recommended!', 5, true, 3),
('James Park', 'VP Marketing', 'GrowthLab', 'The SEO strategy and website redesign SilverArch delivered helped us triple our organic traffic in just 6 months. Their data-driven approach made all the difference.', 5, false, 4);

-- Blog Posts
INSERT INTO public.blog_posts (title, slug, excerpt, content, author_name, category, tags, reading_time, is_published, published_at) VALUES
('Why Next.js is the Future of Web Development', 'why-nextjs-future-web-development', 'Explore why Next.js has become the go-to framework for modern web development and how it can benefit your business.', '## Introduction\n\nNext.js has rapidly become the most popular React framework, and for good reason. With features like server-side rendering, static site generation, and API routes, it provides everything you need to build modern web applications.\n\n## Key Benefits\n\n### Performance\nNext.js automatically optimizes your application with features like code splitting, image optimization, and edge caching.\n\n### Developer Experience\nWith TypeScript support, file-based routing, and built-in API routes, Next.js makes development faster and more enjoyable.\n\n### SEO\nServer-side rendering ensures your content is crawlable by search engines, giving you better rankings out of the box.\n\n## Conclusion\n\nIf you''re building a web application in 2024, Next.js should be at the top of your list. Its combination of performance, developer experience, and flexibility makes it the ideal choice for projects of any size.', 'SilverArch Team', 'Development', '["Next.js", "React", "Web Development"]', 4, true, NOW() - INTERVAL '5 days'),
('The Art of Dark Mode Design', 'art-of-dark-mode-design', 'Learn the principles behind effective dark mode design and how to implement it in your projects.', '## Why Dark Mode?\n\nDark mode isn''t just a trend — it''s a user preference that''s here to stay. Studies show that over 80% of users prefer dark mode when it''s available.\n\n## Design Principles\n\n### Contrast\nMaintain sufficient contrast ratios while avoiding pure white text on pure black backgrounds. Use off-white (#F5F5F7) on dark gray (#0B0B0F) for comfortable reading.\n\n### Elevation\nUse lighter surface colors for elevated elements. This creates a natural depth hierarchy without relying on shadows.\n\n### Accent Colors\nBright, saturated colors work beautifully against dark backgrounds. Use gradients to add visual interest and guide attention.\n\n## Implementation Tips\n\n1. Start with your color palette\n2. Test contrast ratios\n3. Use CSS custom properties for easy theming\n4. Consider user preferences with prefers-color-scheme\n\n## Conclusion\n\nDark mode design is both an art and a science. When done well, it creates an elegant, comfortable experience that users love.', 'SilverArch Team', 'Design', '["UI/UX", "Dark Mode", "Design"]', 3, true, NOW() - INTERVAL '3 days');
